<a href="https://colab.research.google.com/github/w1947567/Week8/blob/main/Water_levels.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

# **Data Cleaning**

# Annual Freshwater Withdrawls

In [ ]:
freshwater_withdrawals_df = pd.read_csv('annual-freshwater-withdrawals.csv')

In [ ]:
freshwater_withdrawals_df.head(10)

,Entity,Code,Year,"Annual freshwater withdrawals, total (billion cubic meters)"
0,Afghanistan,AFG,1975,1.070000e+10
1,Afghanistan,AFG,1976,1.198426e+10
2,Afghanistan,AFG,1977,1.326852e+10
3,Afghanistan,AFG,1978,1.455278e+10
4,Afghanistan,AFG,1979,1.583703e+10
5,Afghanistan,AFG,1980,1.712129e+10
6,Afghanistan,AFG,1981,1.840555e+10
7,Afghanistan,AFG,1982,1.968981e+10
8,Afghanistan,AFG,1983,2.097407e+10
9,Afghanistan,AFG,1984,2.225833e+10

In [ ]:
freshwater_withdrawals_df.duplicated().sum()

0

In [ ]:
freshwater_withdrawals_df.isnull().sum()

Entity                                                          0
Code                                                           78
Year                                                            0
Annual freshwater withdrawals, total (billion cubic meters)     0
dtype: int64

In [ ]:
missing_code_rows = freshwater_withdrawals_df[freshwater_withdrawals_df['Code'].isnull()]

missing_code_rows.sample(20)

,Entity,Code,Year,"Annual freshwater withdrawals, total (billion cubic meters)"
3505,Middle-income countries,NaN,2015,2.828180e+12
1729,Europe and Central Asia (WB),NaN,2014,4.857940e+11
3941,North America (WB),NaN,2016,4.803880e+11
3116,Low-income countries,NaN,2018,1.196610e+11
3506,Middle-income countries,NaN,2016,2.858490e+12
3120,Lower-middle-income countries,NaN,2016,1.643930e+12
2248,High-income countries,NaN,2017,9.280200e+11
3944,North America (WB),NaN,2019,4.806490e+11
1479,East Asia and Pacific (WB),NaN,2018,1.237150e+12
1740,European Union (27),NaN,2019,1.862110e+11
4829,South Asia (WB),NaN,2014,9.213080e+11
1738,European Union (27),NaN,2017,1.881170e+11
2901,Latin America and Caribbean (WB),NaN,2015,4.004130e+11
2905,Latin America and Caribbean (WB),NaN,2019,4.207740e+11
4832,South Asia (WB),NaN,2017,9.264080e+11
2902,Latin America and Caribbean (WB),NaN,2016,4.083920e+11
3942,North America (WB),NaN,2017,4.806490e+11
1735,European Union (27),NaN,2014,1.957260e+11
3114,Low-income countries,NaN,2016,1.188800e+11
4951,Sub-Saharan Africa (WB),NaN,2017,1.275460e+11

In [ ]:
# Replace missing values in the 'Code' column with 'N/A'
freshwater_withdrawals_df['Code'].fillna('N/A', inplace=True)

In [ ]:
freshwater_withdrawals_df.isnull().sum()

Entity                                                         0
Code                                                           0
Year                                                           0
Annual freshwater withdrawals, total (billion cubic meters)    0
dtype: int64

In [ ]:
freshwater_withdrawals_df.dtypes

Entity                                                          object
Code                                                            object
Year                                                             int64
Annual freshwater withdrawals, total (billion cubic meters)    float64
dtype: object

In [ ]:
# List unique entities to check for inconsistencies
unique_entities = freshwater_withdrawals_df['Entity'].unique()
sorted(unique_entities)

['Afghanistan',
 'Albania',
 'Algeria',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Costa Rica',
 "Cote d'Ivoire",
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czechia',
 'Democratic Republic of Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'East Asia and Pacific (WB)',
 'East Timor',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Europe and Central Asia (WB)',
 'European Union (27)',
 'Fiji',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Grenada',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'High-income countries',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latin America and Caribbean (WB)',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Lithuania',
 'Low-income countries',
 'Lower-middle-income countries',
 'Luxembourg',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Middle East and North Africa (WB)',
 'Middle-income countries',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North America (WB)',
 'North Korea',
 'North Macedonia',
 'Norway',
 'Oman',
 'Pakistan',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Somalia',
 'South Africa',
 'South Asia (WB)',
 'South Korea',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sub-Saharan Africa (WB)',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syria',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Togo',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'Upper-middle-income countries',
 'Uruguay',
 'Uzbekistan',
 'Venezuela',
 'Vietnam',
 'World',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [ ]:
freshwater_withdrawals_df.to_csv('freshwater_withdrawals_cleaned.csv', index=False)

 # Premature Deaths

In [ ]:
premature_deaths_df = pd.read_excel('Premature_deaths_due_to_UNSAFE_WASH.xlsx', sheet_name='Sheet1')

In [ ]:
premature_deaths_df.head(10)

       Country  Year  Premature_Death_Count         Risk Health_Impact
0  Afghanistan  1990                  11325  Unsafe WASH          High
1  Afghanistan  1995                  22587  Unsafe WASH          High
2  Afghanistan  2000                  25647  Unsafe WASH          High
3  Afghanistan  2005                  25683  Unsafe WASH          High
4  Afghanistan  2006                  23302  Unsafe WASH          High
5  Afghanistan  2007                  21118  Unsafe WASH          High
6  Afghanistan  2008                  18886  Unsafe WASH          High
7  Afghanistan  2009                  16962  Unsafe WASH          High
8  Afghanistan  2010                  15958  Unsafe WASH          High
9  Afghanistan  2011                  14944  Unsafe WASH          High

In [ ]:
premature_deaths_df.isnull().sum()

Country                  0
Year                     0
Premature_Death_Count    0
Risk                     0
Health_Impact            0
dtype: int64

In [ ]:
premature_deaths_df.duplicated().sum()

0

In [ ]:
unique_countries = premature_deaths_df['Country'].unique()
sorted(unique_countries)

['Afghanistan',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Central African Republic',
 'Chad',
 'Chile',
 "China (People's Republic of)",
 'Colombia',
 'Comoros',
 'Congo',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czechia',
 "CÃ´te d'Ivoire",
 "Democratic People's Republic of Korea",
 'Democratic Republic of the Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'Ghana',
 'Greece',
 'Grenada',
 'Guinea-Bissau']

In [ ]:
premature_deaths_df['Health_Impact'].unique()

array(['High', 'Medium', 'Low'], dtype=object)

In [ ]:
premature_deaths_df.to_csv('premature_deaths_cleaned.csv', index=False)

# Wastewater Discharges

In [ ]:
wastewater_data = pd.read_excel('/content/Wastewater Discharges Per Year Per Country.xlsx', sheet_name='Sheet1')
wastewater_data.head(20)

,Country,Year,Total discharges to Inland waters(million m3),Total discharges to the sea(million m3),"Agricultural (incl. forestry + fisheries) wastewater, all sources, direct discharges(million m3)","Urban wastewater, all sources, discharged without treatment(million m3)","Industrial wastewater, all sources, discharged without treatment(million m3)"
0,Austria,2016,2386.91,0.00,13.50,151.840,39.9247
1,Austria,2018,2314.91,0.00,13.50,137.270,614.5000
2,Austria,2019,2358.63,0.00,13.50,107.550,614.5000
3,Austria,2020,2345.61,0.00,13.50,107.550,39.9247
4,Austria,2021,1505.78,0.00,4.30,112.920,39.9247
5,Czechia,2000,1429.10,383.00,1.40,63.960,19.7575
6,Czechia,2005,1309.80,62.47,1.50,79.420,0.0000
7,Czechia,2010,1367.40,15.78,7.20,121.079,39.9247
8,Czechia,2015,1115.60,0.00,3.40,151.840,56.2500
9,Czechia,2016,1133.90,330.00,4.30,151.840,103.5700
10,Czechia,2017,1168.90,70.12,5.10,112.920,55.0000
11,Czechia,2018,1070.50,16.86,4.50,137.270,55.0000
12,Czechia,2019,1107.50,70.70,3.00,63.960,55.0000
13,Czechia,2020,1166.30,15.78,1.90,62.400,88.9074
14,Czechia,2021,1196.90,324.01,2.10,52.100,88.9074
15,Poland,1980,4681.30,578.00,54.80,112.920,2990.7000
16,Poland,1990,4114.70,942.40,0.10,121.079,579.2600
17,Poland,2000,2501.40,114.00,2.07,79.420,614.5000
18,Poland,2005,2115.10,355.00,1.40,61.720,582.0000
19,Poland,2010,2309.40,65.02,5.84,151.840,553.2000

In [ ]:
wastewater_data.isnull().sum()

Country                                                                                             0
Year                                                                                                0
Total discharges to Inland waters(million m3)                                                       0
Total discharges to the sea(million m3)                                                             0
Agricultural (incl. forestry + fisheries) wastewater, all sources, direct discharges(million m3)    0
Urban wastewater, all sources, discharged without treatment(million m3)                             0
Industrial wastewater, all sources, discharged without treatment(million m3)                        0
dtype: int64

In [ ]:
wastewater_data.duplicated().sum()

0

In [ ]:
wastewater_data.to_csv('wastewater_cleaned.csv', index=False)

# Water Quality

In [ ]:
water_quality_df = pd.read_excel('/content/Proportion of bodies of water with good ambient water quality.xlsx')

water_quality_df.head(15)

,Country Name,Country Code,Series Name,Series Code,1960 [YR1960],1961 [YR1961],1962 [YR1962],1963 [YR1963],1964 [YR1964],1965 [YR1965],...,2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022]
0,Afghanistan,AFG,Proportion of bodies of water with good ambien...,EN.H2O.BDYS.ZS,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1,Albania,ALB,Proportion of bodies of water with good ambien...,EN.H2O.BDYS.ZS,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
2,Algeria,DZA,Proportion of bodies of water with good ambien...,EN.H2O.BDYS.ZS,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
3,Andorra,AND,Proportion of bodies of water with good ambien...,EN.H2O.BDYS.ZS,..,..,..,..,..,..,...,..,..,..,..,92.9,..,..,86,..,..
4,Angola,AGO,Proportion of bodies of water with good ambien...,EN.H2O.BDYS.ZS,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
5,Antigua and Barbuda,ATG,Proportion of bodies of water with good ambien...,EN.H2O.BDYS.ZS,..,..,..,..,..,..,...,..,..,..,..,..,..,..,0,..,..
6,Argentina,ARG,Proportion of bodies of water with good ambien...,EN.H2O.BDYS.ZS,..,..,..,..,..,..,...,..,..,..,..,..,..,..,18,..,..
7,Armenia,ARM,Proportion of bodies of water with good ambien...,EN.H2O.BDYS.ZS,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
8,Australia,AUS,Proportion of bodies of water with good ambien...,EN.H2O.BDYS.ZS,..,..,..,..,..,..,...,..,..,..,..,..,..,..,87.7,..,..
9,Austria,AUT,Proportion of bodies of water with good ambien...,EN.H2O.BDYS.ZS,..,..,..,..,..,..,...,..,..,..,..,80.4,..,..,81.8,..,..
10,Azerbaijan,AZE,Proportion of bodies of water with good ambien...,EN.H2O.BDYS.ZS,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
11,"Bahamas, The",BHS,Proportion of bodies of water with good ambien...,EN.H2O.BDYS.ZS,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
12,Bahrain,BHR,Proportion of bodies of water with good ambien...,EN.H2O.BDYS.ZS,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
13,Bangladesh,BGD,Proportion of bodies of water with good ambien...,EN.H2O.BDYS.ZS,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
14,Barbados,BRB,Proportion of bodies of water with good ambien...,EN.H2O.BDYS.ZS,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..

In [ ]:
water_quality_df.replace("..", pd.NA, inplace=True)

In [ ]:
water_quality_df.duplicated().sum()

2

In [ ]:
water_quality_df[water_quality_df.duplicated()]

,Country Name,Country Code,Series Name,Series Code,1960 [YR1960],1961 [YR1961],1962 [YR1962],1963 [YR1963],1964 [YR1964],1965 [YR1965],...,2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022]
240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Remove duplicate records
water_quality_df.drop_duplicates(inplace=True)

In [ ]:
water_quality_df.isnull().sum()

Country Name       1
Country Code       3
Series Name        3
Series Code        3
1960 [YR1960]    242
                ...
2018 [YR2018]    242
2019 [YR2019]    242
2020 [YR2020]    162
2021 [YR2021]    242
2022 [YR2022]    242
Length: 67, dtype: int64

In [ ]:
# Transform the dataset from wide to long format
water_quality_long_df = pd.melt(water_quality_df, id_vars=['Country Name', 'Country Code', 'Series Name', 'Series Code'],
                                var_name='Year', value_name='Proportion of Good Water Quality')

In [ ]:
# Extract year from the 'Year' column (which currently includes the year and a string '[YRYEAR]')
water_quality_long_df['Year'] = water_quality_long_df['Year'].str.extract('(\d+)').astype(int)

water_quality_long_df.head()

,Country Name,Country Code,Series Name,Series Code,Year,Proportion of Good Water Quality
0,Afghanistan,AFG,Proportion of bodies of water with good ambien...,EN.H2O.BDYS.ZS,1960,<NA>
1,Albania,ALB,Proportion of bodies of water with good ambien...,EN.H2O.BDYS.ZS,1960,<NA>
2,Algeria,DZA,Proportion of bodies of water with good ambien...,EN.H2O.BDYS.ZS,1960,<NA>
3,Andorra,AND,Proportion of bodies of water with good ambien...,EN.H2O.BDYS.ZS,1960,<NA>
4,Angola,AGO,Proportion of bodies of water with good ambien...,EN.H2O.BDYS.ZS,1960,<NA>

In [ ]:
# Keeping only rows with non-null values in the 'Proportion of Good Water Quality' column
water_quality_filtered_df = water_quality_long_df.dropna(subset=['Proportion of Good Water Quality'])

water_quality_filtered_df[water_quality_filtered_df['Proportion of Good Water Quality']<=0]

,Country Name,Country Code,Series Name,Series Code,Year,Proportion of Good Water Quality
14525,Antigua and Barbuda,ATG,Proportion of bodies of water with good ambien...,EN.H2O.BDYS.ZS,2020,0
14700,Uganda,UGA,Proportion of bodies of water with good ambien...,EN.H2O.BDYS.ZS,2020,0

In [ ]:
# Filter out rows where 'Proportion of Good Water Quality' is less than or equal to 0
water_quality_df = water_quality_filtered_df[~(water_quality_filtered_df['Proportion of Good Water Quality'] <= 0)]

In [ ]:
water_quality_filtered_df.to_csv('water_quality_cleaned.csv', index=False)

# Death Rate Per 100k

In [ ]:
death_rate_data = pd.read_csv('/content/death-rates-unsafe-water.csv')

# Display the first few rows of the dataset and its info to understand its structure
death_rate_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6840 entries, 0 to 6839
Data columns (total 4 columns):
 #   Column                                                                                                                     Non-Null Count  Dtype
---  ------                                                                                                                     --------------  -----
 0   Entity                                                                                                                     6840 non-null   object
 1   Code                                                                                                                       6150 non-null   object
 2   Year                                                                                                                       6840 non-null   int64
 3   Deaths that are from all causes attributed to unsafe water source per 100,000 people, in both sexes aged age-standardized  6840 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 213.9+ KB

In [ ]:
death_rate_data.head(5)

,Entity,Code,Year,"Deaths that are from all causes attributed to unsafe water source per 100,000 people, in both sexes aged age-standardized"
0,Afghanistan,AFG,1990,19.733002
1,Afghanistan,AFG,1991,19.332512
2,Afghanistan,AFG,1992,19.326250
3,Afghanistan,AFG,1993,23.127151
4,Afghanistan,AFG,1994,22.089624

In [ ]:
death_rate_data.isnull().sum()

Entity                                                                                                                         0
Code                                                                                                                         690
Year                                                                                                                           0
Deaths that are from all causes attributed to unsafe water source per 100,000 people, in both sexes aged age-standardized      0
dtype: int64

In [ ]:
death_rate_data.duplicated().sum()

0

In [ ]:
# Display rows with missing 'Code' values to investigate possible reasons
missing_code_rows = death_rate_data[death_rate_data['Code'].isnull()]

# Show unique entities with missing codes to understand if there's a pattern
unique_entities_missing_code = missing_code_rows['Entity'].unique()

missing_code_rows.head()

,Entity,Code,Year,"Deaths that are from all causes attributed to unsafe water source per 100,000 people, in both sexes aged age-standardized"
30,African Region (WHO),NaN,1990,159.53082
31,African Region (WHO),NaN,1991,158.74440
32,African Region (WHO),NaN,1992,154.51102
33,African Region (WHO),NaN,1993,151.23440
34,African Region (WHO),NaN,1994,151.40215

In [ ]:
unique_entities_missing_code

array(['African Region (WHO)', 'East Asia & Pacific (WB)',
       'Eastern Mediterranean Region (WHO)', 'England',
       'Europe & Central Asia (WB)', 'European Region (WHO)', 'G20',
       'High Income (WB)', 'Latin America & Caribbean (WB)',
       'Low Income (WB)', 'Lower Middle Income (WB)',
       'Middle East & North Africa (WB)', 'Middle Income (WB)',
       'North America (WB)', 'Northern Ireland', 'OECD Countries',
       'Region of the Americas (WHO)', 'Scotland', 'South Asia (WB)',
       'South-East Asia Region (WHO)', 'Sub-Saharan Africa (WB)', 'Wales',
       'Western Pacific Region (WHO)'], dtype=object)

In [ ]:
# Replace missing 'Code' values with 'N/A'
death_rate_data['Code'].fillna('N/A', inplace=True)
# verify if they are still missing
death_rate_data[death_rate_data['Code'].isnull()]

Empty DataFrame
Columns: [Entity, Code, Year, Deaths that are from all causes attributed to unsafe water source per 100,000 people, in both sexes aged age-standardized]
Index: []

In [ ]:
# Update the column name to be more descriptive
death_rate_data.columns = ['Entity', 'Code', 'Year', 'Unsafe Water Death Rate per 100k']

# Verify the updated column name
death_rate_data.head()

        Entity Code  Year  Unsafe Water Death Rate per 100k
0  Afghanistan  AFG  1990                         19.733002
1  Afghanistan  AFG  1991                         19.332512
2  Afghanistan  AFG  1992                         19.326250
3  Afghanistan  AFG  1993                         23.127151
4  Afghanistan  AFG  1994                         22.089624

In [ ]:
# Check year range
year_range = death_rate_data['Year'].min(), death_rate_data['Year'].max()
year_range

(1990, 2019)

In [ ]:
death_rate_range = death_rate_data['Unsafe Water Death Rate per 100k'].min(), death_rate_data['Unsafe Water Death Rate per 100k'].max()
death_rate_anomalies = death_rate_data[death_rate_data['Unsafe Water Death Rate per 100k'] < 0]

death_rate_anomalies, death_rate_range,

(Empty DataFrame
 Columns: [Entity, Code, Year, Unsafe Water Death Rate per 100k]
 Index: [],
 (0.0018974345, 428.71814))

In [ ]:
unique_countries = death_rate_data['Entity'].unique()
sorted(unique_countries)

['Afghanistan',
 'African Region (WHO)',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Cook Islands',
 'Costa Rica',
 "Cote d'Ivoire",
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czechia',
 'Democratic Republic of Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'East Asia & Pacific (WB)',
 'East Timor',
 'Eastern Mediterranean Region (WHO)',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'England',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Europe & Central Asia (WB)',
 'European Region (WHO)',
 'Fiji',
 'Finland',
 'France',
 'G20',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Greenland',
 'Grenada',
 'Guam',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'High Income (WB)',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latin America & Caribbean (WB)',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Lithuania',
 'Low Income (WB)',
 'Lower Middle Income (WB)',
 'Luxembourg',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia (country)',
 'Middle East & North Africa (WB)',
 'Middle Income (WB)',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Niue',
 'North America (WB)',
 'North Korea',
 'North Macedonia',
 'Northern Ireland',
 'Northern Mariana Islands',
 'Norway',
 'OECD Countries',
 'Oman',
 'Pakistan',
 'Palau',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Region of the Americas (WHO)',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Scotland',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Asia (WB)',
 'South Korea',
 'South Sudan',
 'South-East Asia Region (WHO)',
 'Spain',
 'Sri Lanka',
 'Sub-Saharan Africa (WB)',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Togo',
 'Tokelau',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'United States Virgin Islands',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Vietnam',
 'Wales',
 'Western Pacific Region (WHO)',
 'World',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [ ]:
death_rate_data.to_csv('death_rate_cleaned.csv', index=False)

# **Data Integration**

In [ ]:
wastewater_cleaned_df = pd.read_csv('/content/wastewater_cleaned.csv')
premature_deaths_cleaned_df = pd.read_csv('/content/premature_deaths_cleaned.csv')
death_rate_cleaned_df = pd.read_csv('/content/death_rate_cleaned.csv')
freshwater_withdrawals_cleaned_df = pd.read_csv('/content/freshwater_withdrawals_cleaned.csv')

In [ ]:
# Merge fresh water withdrwals with death rate
merged_df = pd.merge(death_rate_cleaned_df, freshwater_withdrawals_cleaned_df, on=['Entity', 'Year'], how='inner')

merged_df.head()

,Entity,Code_x,Year,Unsafe Water Death Rate per 100k,Code_y,"Annual freshwater withdrawals, total (billion cubic meters)"
0,Afghanistan,AFG,1990,19.733002,AFG,2.452134e+10
1,Afghanistan,AFG,1991,19.332512,AFG,2.399047e+10
2,Afghanistan,AFG,1992,19.326250,AFG,2.346032e+10
3,Afghanistan,AFG,1993,23.127151,AFG,2.293016e+10
4,Afghanistan,AFG,1994,22.089624,AFG,2.240000e+10

In [ ]:
merged_df.shape

(4832, 6)

In [ ]:
merged_df.isnull().sum()

Entity                                                          0
Code_x                                                         18
Year                                                            0
Unsafe Water Death Rate per 100k                                0
Code_y                                                         18
Annual freshwater withdrawals, total (billion cubic meters)     0
dtype: int64

In [ ]:
# Dropping the 'Code_x' and 'Code_y' columns from the merged dataset
merged_df = merged_df.drop(columns=['Code_x', 'Code_y'])

merged_df.head(5)

,Entity,Year,Unsafe Water Death Rate per 100k,"Annual freshwater withdrawals, total (billion cubic meters)"
0,Afghanistan,1990,19.733002,2.452134e+10
1,Afghanistan,1991,19.332512,2.399047e+10
2,Afghanistan,1992,19.326250,2.346032e+10
3,Afghanistan,1993,23.127151,2.293016e+10
4,Afghanistan,1994,22.089624,2.240000e+10

In [ ]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4832 entries, 0 to 4831
Data columns (total 4 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   Entity                                                       4832 non-null   object
 1   Year                                                         4832 non-null   int64
 2   Unsafe Water Death Rate per 100k                             4832 non-null   float64
 3   Annual freshwater withdrawals, total (billion cubic meters)  4832 non-null   float64
dtypes: float64(2), int64(1), object(1)
memory usage: 188.8+ KB

In [ ]:
# Rename the 'Country' column to 'Entity' to match the merged dataset
premature_deaths_cleaned_df = premature_deaths_cleaned_df.rename(columns={'Country': 'Entity'})

# Merge the new dataset with the existing merged dataset
merged_df_2 = pd.merge(merged_df, premature_deaths_cleaned_df, on=['Entity', 'Year'], how='inner')

# Display the first few rows of the final merged dataset to verify
merged_df_2.head(20)

,Entity,Year,Unsafe Water Death Rate per 100k,"Annual freshwater withdrawals, total (billion cubic meters)",Premature_Death_Count,Risk,Health_Impact
0,Afghanistan,1990,19.733002,2.452134e+10,11325,Unsafe WASH,High
1,Afghanistan,1995,24.525007,2.186985e+10,22587,Unsafe WASH,High
2,Afghanistan,2000,27.799639,2.028200e+10,25647,Unsafe WASH,High
3,Afghanistan,2005,23.512026,2.028200e+10,25683,Unsafe WASH,High
4,Afghanistan,2006,21.261396,2.028200e+10,23302,Unsafe WASH,High
5,Afghanistan,2007,18.880657,2.028200e+10,21118,Unsafe WASH,High
6,Afghanistan,2008,16.458422,2.028200e+10,18886,Unsafe WASH,High
7,Afghanistan,2009,14.405564,2.028200e+10,16962,Unsafe WASH,High
8,Afghanistan,2010,13.056941,2.028200e+10,15958,Unsafe WASH,High
9,Afghanistan,2011,11.792764,2.028200e+10,14944,Unsafe WASH,High
10,Afghanistan,2012,10.724737,2.028200e+10,14072,Unsafe WASH,High
11,Afghanistan,2013,10.319930,2.028200e+10,14000,Unsafe WASH,High
12,Afghanistan,2014,9.744861,2.028200e+10,13462,Unsafe WASH,High
13,Afghanistan,2015,9.174777,2.028200e+10,12867,Unsafe WASH,High
14,Afghanistan,2016,8.694507,2.028200e+10,12525,Unsafe WASH,High
15,Afghanistan,2017,8.380472,2.028200e+10,12274,Unsafe WASH,High
16,Afghanistan,2018,7.195067,2.028200e+10,10843,Unsafe WASH,High
17,Afghanistan,2019,6.621417,2.028200e+10,10284,Unsafe WASH,High
18,Albania,1990,1.438939,1.200000e+09,151,Unsafe WASH,Medium
19,Albania,1995,0.879428,1.158900e+09,99,Unsafe WASH,Medium

In [ ]:
merged_df_2.shape

(967, 7)

In [ ]:
merged_df_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 967 entries, 0 to 966
Data columns (total 7 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   Entity                                                       967 non-null    object
 1   Year                                                         967 non-null    int64
 2   Unsafe Water Death Rate per 100k                             967 non-null    float64
 3   Annual freshwater withdrawals, total (billion cubic meters)  967 non-null    float64
 4   Premature_Death_Count                                        967 non-null    int64
 5   Risk                                                         967 non-null    object
 6   Health_Impact                                                967 non-null    object
dtypes: float64(2), int64(2), object(3)
memory usage: 60.4+ KB

In [ ]:
# Rename the 'Country' column to 'Entity' to match the existing merged dataset
wastewater_cleaned_df = wastewater_cleaned_df.rename(columns={'Country': 'Entity'})

# Merge the new dataset with the existing merged dataset
final_merged = pd.merge(merged_df_2, wastewater_cleaned_df, on=['Entity', 'Year'], how='inner')

In [ ]:
final_merged.head(3)

,Entity,Year,Unsafe Water Death Rate per 100k,"Annual freshwater withdrawals, total (billion cubic meters)",Premature_Death_Count,Risk,Health_Impact,Total discharges to Inland waters(million m3),Total discharges to the sea(million m3),"Agricultural (incl. forestry + fisheries) wastewater, all sources, direct discharges(million m3)","Urban wastewater, all sources, discharged without treatment(million m3)","Industrial wastewater, all sources, discharged without treatment(million m3)"
0,Australia,2015,0.097003,9.220000e+09,130,Unsafe WASH,Medium,367.0310,1374.1770,0.5,121.079,55.00
1,Australia,2016,0.093135,1.062300e+10,133,Unsafe WASH,Medium,372.3510,1327.7720,974.1,121.079,62.34
2,Australia,2017,0.089602,1.205864e+10,133,Unsafe WASH,Medium,379.4445,1449.9057,242.6,151.840,72.18

In [ ]:
final_merged['Year'].value_counts()

2016    11
2019    11
2017    10
2018    10
2010    10
2015     9
2005     7
2000     5
1990     2
Name: Year, dtype: int64

In [ ]:
# Check countries with consecutive data from 2015 to 2019
years_required = set(range(2015, 2020))  # Create a set of years from 2015 to 2019

# Filter groups by those that have all the required years
countries_with_consecutive_data = final_merged.groupby('Entity').filter(lambda x: set(x['Year']) >= years_required)['Entity'].unique()

# Display the countries with consecutive data from 2015 to 2019
countries_with_consecutive_data

array(['Australia', 'Belarus', 'Belgium', 'Bulgaria', 'Croatia',
       'Czechia', 'Denmark', 'Estonia'], dtype=object)

In [ ]:
# Find the years available for each country
years_per_country = final_merged.groupby('Entity')['Year'].apply(list)

years_per_country

Entity
Australia                        [2015, 2016, 2017, 2018, 2019]
Austria                                [2010, 2016, 2018, 2019]
Belarus                    [2010, 2015, 2016, 2017, 2018, 2019]
Belgium        [2000, 2005, 2010, 2015, 2016, 2017, 2018, 2019]
Brazil               [1990, 2000, 2005, 2010, 2015, 2016, 2017]
Bulgaria      [1990, 2000, 2005, 2010, 2015, 2016, 2017, 201...
Canada                                                   [2005]
Chile                                                    [2010]
Costa Rica                             [2016, 2017, 2018, 2019]
Croatia              [2005, 2010, 2015, 2016, 2017, 2018, 2019]
Czechia        [2000, 2005, 2010, 2015, 2016, 2017, 2018, 2019]
Denmark                    [2010, 2015, 2016, 2017, 2018, 2019]
Estonia        [2000, 2005, 2010, 2015, 2016, 2017, 2018, 2019]
France                                                   [2019]
Name: Year, dtype: object

In [ ]:
# Subset the dataset to include only the specified countries
countries_to_include = [
    'Australia',
    'Belarus',
    'Belgium',
    'Bulgaria',
    'Croatia',
    'Czechia',
    'Denmark',
    'Estonia',
    'Costa Rica'
]

subset_df = final_merged[final_merged['Entity'].isin(countries_to_include)]

subset_df.head()

,Entity,Year,Unsafe Water Death Rate per 100k,"Annual freshwater withdrawals, total (billion cubic meters)",Premature_Death_Count,Risk,Health_Impact,Total discharges to Inland waters(million m3),Total discharges to the sea(million m3),"Agricultural (incl. forestry + fisheries) wastewater, all sources, direct discharges(million m3)","Urban wastewater, all sources, discharged without treatment(million m3)","Industrial wastewater, all sources, discharged without treatment(million m3)"
0,Australia,2015,0.097003,9.220000e+09,130,Unsafe WASH,Medium,367.0310,1374.1770,0.5000,121.079,55.00
1,Australia,2016,0.093135,1.062300e+10,133,Unsafe WASH,Medium,372.3510,1327.7720,974.1000,121.079,62.34
2,Australia,2017,0.089602,1.205864e+10,133,Unsafe WASH,Medium,379.4445,1449.9057,242.6000,151.840,72.18
3,Australia,2018,0.087649,1.242540e+10,135,Unsafe WASH,Medium,324.3432,1359.3658,169.3235,151.840,55.00
4,Australia,2019,0.085156,9.782612e+09,138,Unsafe WASH,Medium,303.2444,1352.0805,38.5000,107.550,55.00

In [ ]:
# Further filter the subset to keep only the years from 2015 to 2019
subset_df_2015_2019 = subset_df[(subset_df['Year'] >= 2015) & (subset_df['Year'] <= 2019)]

subset_df_2015_2019.tail(5)

,Entity,Year,Unsafe Water Death Rate per 100k,"Annual freshwater withdrawals, total (billion cubic meters)",Premature_Death_Count,Risk,Health_Impact,Total discharges to Inland waters(million m3),Total discharges to the sea(million m3),"Agricultural (incl. forestry + fisheries) wastewater, all sources, direct discharges(million m3)","Urban wastewater, all sources, discharged without treatment(million m3)","Industrial wastewater, all sources, discharged without treatment(million m3)"
69,Estonia,2015,0.046188,1.615343e+09,5,Unsafe WASH,Low,213.42,70.70,48.81,52.10,51.25
70,Estonia,2016,0.048265,1.751400e+09,5,Unsafe WASH,Low,53.07,70.35,0.11,45.08,55.00
71,Estonia,2017,0.043768,1.784900e+09,5,Unsafe WASH,Low,52.65,74.05,0.49,7.39,72.18
72,Estonia,2018,0.041059,1.608540e+09,5,Unsafe WASH,Low,45.00,63.63,32.50,49.40,56.25
73,Estonia,2019,0.038807,1.006450e+09,5,Unsafe WASH,Low,47.84,70.94,0.08,8.65,56.25

In [ ]:
# Costa Rica's data for 2016 exists and will be used for 2015
# Find Costa Rica's 2016 data
costa_rica_2016_data = subset_df_2015_2019[(subset_df_2015_2019['Entity'] == 'Costa Rica') & (subset_df_2015_2019['Year'] == 2016)]

# Copy 2016 data to create a 2015 entry
nocf_2015_data = costa_rica_2016_data.copy()
nocf_2015_data['Year'] = 2015

# Append the NOCF data to the dataset
subset_df_2015_2019 = pd.concat([subset_df_2015_2019, nocf_2015_data], ignore_index=True)

# Sort the dataset if necessary
subset_df_2015_2019 = subset_df_2015_2019.sort_values(by=['Entity', 'Year'])

In [ ]:
subset_df_2015_2019.head(5)

,Entity,Year,Unsafe Water Death Rate per 100k,"Annual freshwater withdrawals, total (billion cubic meters)",Premature_Death_Count,Risk,Health_Impact,Total discharges to Inland waters(million m3),Total discharges to the sea(million m3),"Agricultural (incl. forestry + fisheries) wastewater, all sources, direct discharges(million m3)","Urban wastewater, all sources, discharged without treatment(million m3)","Industrial wastewater, all sources, discharged without treatment(million m3)"
0,Australia,2015,0.097003,9.220000e+09,130,Unsafe WASH,Medium,367.0310,1374.1770,0.5000,121.079,55.00
1,Australia,2016,0.093135,1.062300e+10,133,Unsafe WASH,Medium,372.3510,1327.7720,974.1000,121.079,62.34
2,Australia,2017,0.089602,1.205864e+10,133,Unsafe WASH,Medium,379.4445,1449.9057,242.6000,151.840,72.18
3,Australia,2018,0.087649,1.242540e+10,135,Unsafe WASH,Medium,324.3432,1359.3658,169.3235,151.840,55.00
4,Australia,2019,0.085156,9.782612e+09,138,Unsafe WASH,Medium,303.2444,1352.0805,38.5000,107.550,55.00

In [ ]:
# Filter for Czechia and the specific column
czechia_sea_discharges = subset_df_2015_2019[(subset_df_2015_2019['Entity'] == 'Czechia')]['Total discharges to the sea(million m3)']

# Calculate the mean, excluding zeros
mean_czechia_sea_discharges = czechia_sea_discharges[czechia_sea_discharges != 0].mean()

# Replace the zero value for Czechia in 2015 with the mean
subset_df_2015_2019.loc[(subset_df_2015_2019['Entity'] == 'Czechia') & (subset_df_2015_2019['Year'] == 2015) & (subset_df_2015_2019['Total discharges to the sea(million m3)'] == 0), 'Total discharges to the sea(million m3)'] = mean_czechia_sea_discharges

In [ ]:
# Rename the dataframe to a more suitable name representing the whole dataset
water_related_dataset = subset_df_2015_2019.copy()

In [ ]:
# Remove the "Risk" column from the water_related_dataset
water_related_dataset = water_related_dataset.drop(columns=['Risk'])


water_related_dataset.head()

,Entity,Year,Unsafe Water Death Rate per 100k,"Annual freshwater withdrawals, total (billion cubic meters)",Premature_Death_Count,Health_Impact,Total discharges to Inland waters(million m3),Total discharges to the sea(million m3),"Agricultural (incl. forestry + fisheries) wastewater, all sources, direct discharges(million m3)","Urban wastewater, all sources, discharged without treatment(million m3)","Industrial wastewater, all sources, discharged without treatment(million m3)"
0,Australia,2015,0.097003,9.220000e+09,130,Medium,367.0310,1374.1770,0.5000,121.079,55.00
1,Australia,2016,0.093135,1.062300e+10,133,Medium,372.3510,1327.7720,974.1000,121.079,62.34
2,Australia,2017,0.089602,1.205864e+10,133,Medium,379.4445,1449.9057,242.6000,151.840,72.18
3,Australia,2018,0.087649,1.242540e+10,135,Medium,324.3432,1359.3658,169.3235,151.840,55.00
4,Australia,2019,0.085156,9.782612e+09,138,Medium,303.2444,1352.0805,38.5000,107.550,55.00

In [ ]:
# Export the dataframe to a CSV file
water_related_dataset.to_csv('integrated_water_related_data.csv', index=False)